// Opt-in network smoke test. Start `npm run dev` first; no CarAPI credentials required.
import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import { chromium } from 'playwright';

const base = process.env.E2E_BASE_URL || 'http://127.0.0.1:5173';
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
const page = await context.newPage();
page.setDefaultTimeout(75000);
const errors = [];
const externalCalls = [];
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => { if (request.url().startsWith('https://carapi.app/api')) externalCalls.push(request.url()); });
const resultsReady = () => page.locator('.comparison-total-row').waitFor();
try {
  await page.goto(base);
  await resultsReady();
  assert.equal(await page.locator('.demo-notice').count(), 0);
  assert.match(await page.locator('.data-status').innerText(), /Catalogue connecté/);
  const initial = await page.locator('.vehicle-card').count();
  assert.equal(initial, 12);
  const firstPage = await page.locator('.vehicle-card').allTextContents();
  const initialSelection = await page.evaluate(() => JSON.parse(localStorage.getItem('autocompare_tco_state')).selectedIds);
  assert.equal(await page.getByRole('button', { name: 'Précédent', exact: true }).isDisabled(), true);
  await page.getByRole('button', { name: 'Suivant', exact: true }).click();
  await page.locator('.catalog-pagination p').filter({ hasText: /page 2 sur/ }).waitFor();
  await resultsReady();
  assert.equal(await page.locator('.vehicle-card').count(), 12);
  assert.notDeepEqual(await page.locator('.vehicle-card').allTextContents(), firstPage);
  assert.deepEqual(await page.evaluate(() => JSON.parse(localStorage.getItem('autocompare_tco_state')).selectedIds), initialSelection);
  assert.equal(await page.locator('.comparison-total-row td').count(), initialSelection.length);
  assert.equal(await page.evaluate(() => document.activeElement?.id), 'catalog-title');
  assert.ok(await page.locator('#catalog-title').evaluate(element => element.getBoundingClientRect().top >= 0 && element.getBoundingClientRect().top < innerHeight));
  await page.getByRole('button', { name: 'Précédent', exact: true }).click();
  await page.locator('.catalog-pagination p').filter({ hasText: /page 1 sur/ }).waitFor();
  await resultsReady();
  assert.deepEqual(await page.locator('.vehicle-card').allTextContents(), firstPage);
  await page.getByRole('spinbutton', { name: 'Aller à la page' }).fill('15');
  await page.getByRole('button', { name: 'Aller', exact: true }).click();
  await page.locator('.catalog-pagination p').filter({ hasText: /page 15 sur/ }).waitFor();
  await resultsReady();
  assert.equal(await page.locator('.vehicle-card').count(), 12);
  assert.deepEqual(await page.evaluate(() => JSON.parse(localStorage.getItem('autocompare_tco_state')).selectedIds), initialSelection);
  await page.getByRole('spinbutton', { name: 'Aller à la page' }).fill('1');
  await page.getByRole('button', { name: 'Aller', exact: true }).click();
  await page.locator('.catalog-pagination p').filter({ hasText: /page 1 sur/ }).waitFor();
  await resultsReady();
  await page.getByRole('button', { name: 'Tout effacer' }).click();
  await page.getByRole('combobox', { name: 'Marque CarAPI', exact: true }).fill('Tes');
  await page.getByRole('option', { name: 'Tesla', exact: true }).click();
  await page.getByRole('combobox', { name: 'Modèle CarAPI', exact: true }).focus();
  await page.getByRole('option', { name: 'Model 3', exact: true }).click();
  const search = page.waitForResponse(response => response.url().includes('/api/vehicules?') && response.url().includes('make=Tesla'));
  await page.locator('.remote-search').getByRole('button', { name: 'Rechercher' }).click();
  const remote = await (await search).json();
  assert.ok(remote.data.length > 0);
  assert.ok(remote.data.every(v => v.marque === 'Tesla' && v.source === 'carapi' && v.annee === 2020));
  const photo = page.locator('.vehicle-card .verified-photo').first();
  await photo.scrollIntoViewIfNeeded();
  await photo.evaluate(img => img.decode());
  assert.ok(await photo.evaluate(img => img.naturalWidth > 0));
  await page.locator('.vehicle-card:not(:disabled)').first().click();
  await resultsReady();
  assert.equal(await page.locator('.vehicle-card').count(), remote.data.length);
  assert.equal(await page.getByRole('button', { name: 'Suivant', exact: true }).isDisabled(), true);
  await page.locator('.estimation-editor summary').click();
  await page.getByLabel('Prix d’achat envisagé', { exact: true }).fill('24000');
  await page.getByLabel('Revente estimée après 5 ans', { exact: true }).fill('12000');
  await page.getByLabel('Consommation en usage réel', { exact: true }).fill('20');
  await page.getByLabel('Prix de l’énergie', { exact: true }).fill('0.25');
  const [personalizedResponse] = await Promise.all([
    page.waitForResponse(response => response.url().endsWith('/api/simulation') && response.request().postDataJSON()?.ajustements),
    page.getByRole('button', { name: 'Appliquer au comparatif' }).click(),
  ]);
  assert.equal(personalizedResponse.status(), 200);
  const personalized = (await personalizedResponse.json()).resultats[0];
  assert.equal(personalized.cout_total, 23750);
  assert.equal(personalized.hypotheses_appliquees.prix_achat, 24000);
  assert.equal(personalized.hypotheses_appliquees.valeur_revente, 12000);
  await resultsReady();
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('autocompare_tco_state')));
  assert.ok(stored.selectedIds[0].startsWith('carapi_'));
  await page.reload();
  await resultsReady();
  assert.deepEqual(await page.evaluate(() => JSON.parse(localStorage.getItem('autocompare_tco_state')).selectedIds), stored.selectedIds);
  assert.equal(await page.locator('.vehicle-card').count(), 12);
  assert.equal(await page.locator('.vehicle-card[aria-pressed="true"]').count(), 0);
  assert.match(await page.locator('.comparison-table thead').innerText(), /Tesla/i);
  assert.equal(await page.locator('.comparison-total-row td').innerText(), (23750).toLocaleString('fr-FR') + ' €');
  assert.deepEqual(await page.evaluate(() => JSON.parse(localStorage.getItem('autocompare_tco_state')).params.ajustements), stored.params.ajustements);
  await page.getByText('Comprendre les hypothèses du calcul', { exact: true }).click();
  assert.match(await page.locator('.calculation-assumptions').innerText(), /CarAPI ne fournit ni simulation/);
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Télécharger mon comparatif' }).click();
  const pdf = await download;
  await mkdir('output/screenshots', { recursive: true });
  await pdf.saveAs('output/carapi-live.pdf');
  assert.equal((await readFile('output/carapi-live.pdf')).subarray(0, 4).toString(), '%PDF');
  await page.locator('.carapi-browser').evaluate(element => element.scrollIntoView({ block: 'start', behavior: 'instant' }));
  await page.screenshot({ path: 'output/screenshots/carapi-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('.carapi-browser').evaluate(element => element.scrollIntoView({ block: 'start', behavior: 'instant' }));
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  await page.screenshot({ path: 'output/screenshots/carapi-mobile.png' });
  assert.deepEqual(errors, []);
  assert.deepEqual(externalCalls, []);
  console.log('PASS live CarAPI: 12 cards per page, direct page navigation, preserved off-page selection, focus/scroll, page boundaries, live brand/model suggestions, Tesla photos, personalized simulation and persistence, PDF, mobile, same-origin calls.');
} finally { await browser.close(); }
