// Run against a local production preview or, later, the actual Vercel preview URL.
import assert from 'node:assert/strict';
const base = process.env.E2E_BASE_URL || 'http://127.0.0.1:4173';
const request = (path, options) => fetch(new URL(path, base), { signal: AbortSignal.timeout(70000), ...options });
const health = await request('/api/health');
assert.equal(health.status, 200);
assert.equal((await health.json()).service, 'autocompare');
assert.ok(health.headers.get('x-request-id'));
const catalogue = await request('/api/vehicules?year=2020&make=Toyota&model=Camry');
assert.equal(catalogue.status, 200);
const data = await catalogue.json();
assert.ok(data.data.length > 0 && data.data.length <= 12);
assert.equal(data.meta.source, 'carapi');
const vehicle = data.data.find(item => item.simulable);
assert.ok(vehicle, 'A real vehicle must be available for the deployment check');
const detail = await request(`/api/vehicules/${vehicle.id}`);
assert.equal(detail.status, 200);
assert.equal((await detail.json()).id, vehicle.id);
const params = { vehicule_ids: [vehicle.id], kilometrage_annuel: 15000, duree_annees: 5, region: 'FR' };
const simulation = await request('/api/simulation', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(params) });
assert.equal(simulation.status, 200);
assert.equal((await simulation.json()).resultats[0].vehicule_id, vehicle.id);
assert.equal((await request('/api/simulation')).status, 405);
assert.equal((await request('/api/vehicules?year=invalid')).status, 400);
assert.equal((await request('/api/vehicules/carapi_0')).status, 404);
assert.equal((await request('/api/simulation', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{' })).status, 400);
const html = await request('/');
assert.equal(html.status, 200);
assert.match(await html.text(), /AutoCompare/);
console.log(`PASS deployment routes, real CarAPI catalogue/detail/simulation and HTTP errors: ${base}`);
