import { Building2, CarFront, Route, CalendarDays, MapPin, SlidersHorizontal, RotateCcw } from 'lucide-react';
const PRESETS = [
  { label: 'En ville', km: 8000, years: 3, Icon: Building2 },
  { label: 'Au quotidien', km: 15000, years: 5, Icon: CarFront },
  { label: 'Grand rouleur', km: 30000, years: 4, Icon: Route },
];
export default function SimulationControls({ params, onChange, onApplyPreset }) {
  return <aside className="usage-panel" aria-labelledby="usage-title" id="mon-usage">
    <div className="panel-heading"><span className="section-step">02</span><span className="eyebrow">VOTRE QUOTIDIEN</span><SlidersHorizontal size={17} /></div>
    <h2 id="usage-title">À chacun sa route.</h2><p className="panel-intro">Quelques détails sur votre usage pour une comparaison qui vous ressemble.</p>
    <div className="preset-label">Votre profil de conduite</div><div className="presets" role="group" aria-label="Profils de conduite">{PRESETS.map(({ label, km, years, Icon }) => <button key={label} className={`preset ${params.kilometrage_annuel === km && params.duree_annees === years ? 'is-active' : ''}`} aria-pressed={params.kilometrage_annuel === km && params.duree_annees === years} onClick={() => onApplyPreset(km, years)}><Icon size={17} /><span>{label}</span></button>)}</div>
    <div className="usage-field"><label htmlFor="annual-distance"><Route size={16} /> Kilométrage annuel</label><div className="range-value"><output htmlFor="annual-distance">{params.kilometrage_annuel.toLocaleString('fr-FR')}</output><span>km / an</span></div><input id="annual-distance" type="range" min="2000" max="60000" step="1000" value={params.kilometrage_annuel} onChange={e => onChange({ ...params, kilometrage_annuel: Number(e.target.value) })} aria-valuetext={`${params.kilometrage_annuel} kilomètres par an`} style={{ '--range-progress': `${(params.kilometrage_annuel - 2000) / 580}%` }} /><div className="range-bounds"><span>2 000 km</span><span>60 000 km</span></div></div>
    <div className="usage-field"><label htmlFor="ownership-years"><CalendarDays size={16} /> Durée de possession</label><div className="range-value"><output htmlFor="ownership-years">{params.duree_annees}</output><span>{params.duree_annees > 1 ? 'années' : 'année'}</span></div><input id="ownership-years" type="range" min="1" max="15" step="1" value={params.duree_annees} onChange={e => onChange({ ...params, duree_annees: Number(e.target.value) })} aria-valuetext={`${params.duree_annees} ans`} style={{ '--range-progress': `${(params.duree_annees - 1) / 14 * 100}%` }} /><div className="range-bounds"><span>1 an</span><span>15 ans</span></div></div>
    <div className="usage-field region-field"><label htmlFor="region"><MapPin size={16} /> Votre pays</label><select id="region" value={params.region} onChange={e => onChange({ ...params, region: e.target.value })}><option value="FR">France</option><option value="BE">Belgique</option><option value="DE">Allemagne</option><option value="CH">Suisse</option><option value="ES">Espagne</option></select><small>Scénario de prix d’énergie indicatif, sans tarif en temps réel.</small></div>
    <div className="usage-summary"><Route size={19} /><p>Votre horizon de comparaison<strong>{(params.kilometrage_annuel * params.duree_annees).toLocaleString('fr-FR')} km sur {params.duree_annees} ans</strong></p></div><button className="reset-button" onClick={() => onChange({ ...params, kilometrage_annuel: 15000, duree_annees: 5, region: 'FR' })}><RotateCcw size={13} /> Réinitialiser mon profil</button>
  </aside>;
}
